version: '3'
services:
  api:
    container_name: banner-service
    build: .
    environment:
      - APP_ENV=development
    ports:
      - '4000:4000'
    depends_on:
      - redis
    volumes:
      - ./server/:/app/server/
      - ./public/:/app/public/
      - ./ui/:/app/ui/
    command: run dev
    depends_on:
      - redis

  redis:
    container_name: banner-redis
    image: redis:alpine
    ports:
      - '6379:6379'
